apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes: 
        - name: config-volume
          configMap:
            name: app-config
        - name: secret-volume
          secret:
            secretName: app-secret
      containers:
      - name: nginx
        image: nginx:1.29
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
          - name: secret-volume
            mountPath: /etc/secrets
            readOnly: true

        env:
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: username

          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: password
        
        