apiVersion: v1
kind: Service

metadata:
  name: postgres-headless

spec:
  clusterIP: None

  selector:
    app: postgres

  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgres

spec:
  serviceName: postgres-headless

  replicas: 3

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres

          image: postgres:18

          env:
            - name: POSTGRES_USER
              value: demo

            - name: POSTGRES_PASSWORD
              value: CHANGE_ME_DEMO_PASSWORD

            - name: POSTGRES_DB
              value: demo

          ports:
            - name: postgres
              containerPort: 5432

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql

  volumeClaimTemplates:

    - metadata:
        name: postgres-data

      spec:
        accessModes:
          - ReadWriteOnce

        storageClassName: standard

        resources:
          requests:
            storage: 1Gi